### ISSUE TITLE
DerivedCategories as a collection of packages?

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/DerivedCategories#13]
Do you believe that it is a good idea to bundle all your packages which are related to `DerivedCategories` into a single repository, just like we did with `CAP_project`?
That would involve packages like
- DerivedCategories
- TriangulatedCategories
- StableCategories
- QuotientCategories
- ModelCategories
- HomotopyCategories
- FrobeniusCategories
- ComplexesCategories
- BBGG
which to my knowledge are all quite interdependent. 

That would make the update process for the user much easier.

**Comment by kamalsaleh** [comment]
Thank you Sebastian, I think it is a great idea and in the right time also. I just need a representative name for the main repository, what would you name it?. I would also like to hear @mohamed-barakat 's opinion about this.

**Comment by sebastianpos** [comment]
I'm glad that you like the idea. The name could refer somehow to the categorical homological algebra concepts that you provide.
Something like `HigherHomologicalAlgebra(ForCAP)`?

**Comment by kamalsaleh** [comment]
Also other possibilities are

- `AHA` for Algorithmic Homological algebra (it is symmetric)
- `CHA` for computational, categorical or constructive homological algeba (it is not symmetric)
- `cohomalg` for constructive homological algeba (we can then tell people we have now homalg and cohomalg :smile:)

Let us wait and see Mohamed 's opinion

**Comment by mohamed-barakat** [comment]
I prefer explicit names. I am in favor of `HigherHomologicalAlgebra` without the `ForCAP` extension, which is by now a tautology.

**Comment by mohamed-barakat** [comment]
Please follow @zickgraf's guidelines for merging existing repositories for `homalg_stats` to work properly.

**Comment by kamalsaleh** [comment]
I have already created a repository [HigherHomologicalAlgebra](https://github.com/kamalsaleh/HigherHomologicalAlgebra) which currently contains

- BBGG
- Bicomplexes
- ComplexesCategories
- QuotientCategories
- StableCategories
- TriangulatedCategories
- HomotopyCategories
- DerivedCategories

The packages `ModelCategories` and `FrobeniusCategories` will be added later, since they have not been udpated for ages and currently, there is no concrete use/application of them.

I also rebased many packages to do some fixes and unify my three names:` Kamal Saleh`, `Kamal`, `kamalsaleh`.

**Comment by kamalsaleh** [comment]
@zickgraf could you please check whether your script at `homalg_stats` runs as expected with the new repository and let me know if any changes should be taken?

**Comment by zickgraf** [comment]
Looks fine, `homalg_stats` runs without errors, and the graph has no weird bumps :-)

Two optional notes:
1. You are not using subtree merges as far as I can tell. This is not a problem for the script because your manual merges are "clean"! :-) But subtree merges would be the method officially supported by git. An example would be executing
```
git subtree add --prefix=QuotientCategories /path/to/QuotientCategories master
git subtree add --prefix=StableCategories /path/to/StableCategories master
...
```
(starting in an empty repository).

2. I would suggest creating the new repository directly under `homalg_project` and forking to your own account, not the other way round.

**Comment by mohamed-barakat** [comment]
Thank you very much Fabian.

@kamalsaleh: Please use the subtree merge as suggested by Fabian.

I think it is ok if you create the repo first as one of your repos, then I'll clone it to homalg_project and then grant you admin rights. You can then delete yours and fork it again (the usual procedure).

**Comment by mohamed-barakat** [comment]
FYI: Once the repo exists I need to make a new release of `HomalgProject.jl`. I am not yet sure what to do with the old repos. At some point, they should be deleted, but I am worried about deleting them right away, as this may cause problems with older used versions of `HomalgProject.jl`.

**Comment by kamalsaleh** [comment]
Thank you @zickgraf, it is indeed more convenient  than `git merge $x/master --allow-unrelated-histories`,  the latter does not create a new directory for each `repo`, and `homalg_stats` runs also as expected with `subtree merges`. @mohamed-barakat  I believe you can now fork the package to `homalg_project`

**Comment by mohamed-barakat** [comment]
> @mohamed-barakat I believe you can now fork the package to `homalg_project`

Done. Thank you very much.
